# Generated by Django 5.0.14 on 2026-08-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_sample_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("RECEIVED", "Received"),
                    ("IN_TESTING", "In testing"),
                    ("COMPLETE", "Complete"),
                    ("DISPOSED", "Disposed"),
                ],
                default="RECEIVED",
                max_length=20,
            ),
        ),
    ]
