# Generated by Django 5.0.14 on 2026-09-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_instrument_last_calibrated_at_calibrationrecord"),
        ("labtests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                help_text="Which instrument produced this reading, if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_results",
                to="catalog.instrument",
            ),
        ),
    ]
