# Generated by Django 5.0.14 on 2026-08-22 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code, e.g. GAS95, DIESEL, JETA1",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "instrument_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Gas Chromatograph, Densitometer",
                        max_length=100,
                    ),
                ),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("OUT_OF_SERVICE", "Out of service"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("calibration_due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short internal code, e.g. FLASH-D93",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Flash Point (Pensky-Martens Closed Cup)",
                        max_length=150,
                    ),
                ),
                (
                    "standard_reference",
                    models.CharField(help_text="e.g. ASTM D93 / IP 34", max_length=100),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g. °C, kg/m³, mg/kg, kPa, mm²/s", max_length=30
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpecLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True,
                        help_text="Leave blank if there is no minimum",
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True,
                        help_text="Leave blank if there is no maximum",
                        null=True,
                    ),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_limits",
                        to="catalog.fueltype",
                    ),
                ),
                (
                    "test_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_limits",
                        to="catalog.testmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["fuel_type__name", "test_method__name"],
                "unique_together": {("test_method", "fuel_type")},
            },
        ),
    ]
