# Generated by Django 5.0.14 on 2026-09-11 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_astm_scope_corrections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="last_calibrated_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CalibrationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_at",
                    models.DateField(
                        help_text="Date the calibration was actually performed"
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if this instrument doesn't need recurring calibration",
                        null=True,
                    ),
                ),
                (
                    "certificate_reference",
                    models.CharField(
                        blank=True,
                        help_text="Calibration certificate or work order number, if any",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_records",
                        to="catalog.instrument",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calibrations_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at", "-created_at"],
            },
        ),
    ]
