# Generated by Django 5.0.14 on 2026-08-27 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a client-portal account so this sample (and its certificate) shows up in their portal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples",
                to="accounts.client",
            ),
        ),
    ]
