# Generated by Django 5.0.14 on 2026-09-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_alter_sample_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="destination_port",
            field=models.CharField(
                blank=True,
                help_text="Destination port or delivery point.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="origin",
            field=models.CharField(
                blank=True,
                help_text="Where the fuel originated — refinery, depot, terminal, etc.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("TANK", "Storage tank"), ("ROAD_TANKER", "Road tanker")],
                help_text="What the sample was physically drawn from.",
                max_length=20,
                verbose_name="Drawn from",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="tank_or_tanker_id",
            field=models.CharField(
                blank=True,
                help_text="The storage tank number or road tanker's fleet/unit ID.",
                max_length=100,
                verbose_name="Tank / tanker ID",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="tanker_plate_number",
            field=models.CharField(
                blank=True,
                help_text="Required if drawn from a road tanker.",
                max_length=20,
                verbose_name="Road tanker plate number",
            ),
        ),
    ]
